Random values




In [8]:

import torch
import numpy
from sympy.codegen.ast import float128

print("hello world")
x = torch.rand(5,3)
print(f"torch rand: {x}")

hello world
torch rand: tensor([[0.3298, 0.2070, 0.4165],
        [0.7053, 0.9473, 0.9123],
        [0.5932, 0.9072, 0.6709],
        [0.0867, 0.3125, 0.8146],
        [0.6255, 0.9152, 0.5632]])


ZEROS

In [7]:
x = torch.zeros(5,3)
print(f"torch zeros: {x}")

torch zeros: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])





Check size

In [12]:
print(f"size: {torch.rand(2,3).size()}")  #metoda
print(f"shape: {torch.zeros(5,2).shape}") #atrybut

size: torch.Size([2, 3])
shape: torch.Size([5, 2])



Check data type

In [16]:
x = torch.rand(3,1)
print(f"Data type {x.dtype}")

x = torch.zeros(5,3, dtype= torch.float16)
print(x)
print(f"Data type: {x.dtype}")

Data type torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
Data type: torch.float16







Construct from data

In [17]:
x = torch.tensor([5.5,3])
print(f"{x} {x.dtype}")

tensor([5.5000, 3.0000]) torch.float32


requires_grad argument
This will tell pyTorch that it will be needed to calculate thr gratients for this tensor

In [22]:
x = torch.tensor([4.5,3], requires_grad=True)
print(x)
print(x.requires_grad)

tensor([4.5000, 3.0000], requires_grad=True)
True


Operations with tensors

In [25]:
x = torch.ones(2,2)
y = torch.rand(2,2)

print(x)
print(y)

#addition
z = x + y
print(z)
#subtraction
z = x - y
print(z)
#multiplication
z = x * y
print(z)



tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5976, 0.7648],
        [0.4893, 0.8827]])
tensor([[1.5976, 1.7648],
        [1.4893, 1.8827]])
tensor([[0.4024, 0.2352],
        [0.5107, 0.1173]])
tensor([[0.5976, 0.7648],
        [0.4893, 0.8827]])


Slicing

In [31]:
x = torch.rand(5,2)
print(x)
print(f"x[:, 0], {x[:, 0]}") # all rows column == 0
print(f"x[:, 1], {x[:, 1]}") # all rows column == 1
print(f"x[1, 1], {x[1, 1]}") # element at position (1, 1) | returns a tensor object (scalar tensor) at that position

print(f"x[1,1].item() {x[1,1].item()}") # returns the Python value (float/int) at that position


tensor([[0.9700, 0.1777],
        [0.7729, 0.2997],
        [0.8850, 0.8260],
        [0.2906, 0.4037],
        [0.5179, 0.9069]])
x[:, 0], tensor([0.9700, 0.7729, 0.8850, 0.2906, 0.5179])
x[:, 1], tensor([0.1777, 0.2997, 0.8260, 0.4037, 0.9069])
x[1, 1], torch.float32
x[1,1].item() 0.29970085620880127


Reshape with torch.view()

In [44]:
2# nazwa tych struktur to sa ogolnie SHAPE

x = torch.rand(4,4)
print(x)
print()
y = x.view(16)
print(y)
print()

z = x.view(-1, 4)   # -1 in PyTorch is a magic number that meas count by ur self
print(z)
print()

print(x.size(), y.size(), z.size())


tensor([[1.0345e-01, 4.5794e-01, 6.9606e-04, 2.4512e-01],
        [5.0567e-01, 8.7240e-01, 7.2844e-01, 5.6316e-01],
        [5.7201e-01, 4.0728e-01, 6.6007e-01, 9.8726e-02],
        [3.2219e-01, 1.5198e-01, 3.1081e-02, 5.9530e-01]])

tensor([1.0345e-01, 4.5794e-01, 6.9606e-04, 2.4512e-01, 5.0567e-01, 8.7240e-01,
        7.2844e-01, 5.6316e-01, 5.7201e-01, 4.0728e-01, 6.6007e-01, 9.8726e-02,
        3.2219e-01, 1.5198e-01, 3.1081e-02, 5.9530e-01])

tensor([[1.0345e-01, 4.5794e-01, 6.9606e-04, 2.4512e-01],
        [5.0567e-01, 8.7240e-01, 7.2844e-01, 5.6316e-01],
        [5.7201e-01, 4.0728e-01, 6.6007e-01, 9.8726e-02],
        [3.2219e-01, 1.5198e-01, 3.1081e-02, 5.9530e-01]])

torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


# ---- NumPy----


In [2]:
import numpy
import torch

a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(f"{b} {type(b)}")

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


 If tensor is on the CPU (not on GPU)
 Both objects will share the same memory location, so changing one
 will also change the other

In [3]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy to torch with .from_numpy ; torch.tensor

In [5]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)     # reference
c = torch.tensor(a)         # copy of it

print(a)
print(b)
print(c)

a += 1                      #be cerful when modifying
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# GPU Support

In [6]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# in case we have more than one cuda GPU we can use 'cuda:0' etc..

x = torch.rand(2,2).to(device) # moves tensors to GPU device
# x = x.to("cpu")
# x = x.to("cuda")

x = torch.rand(2,2, device=device)

# Autograd
requires_grad = True -> tracks all operations on the tensor

In [4]:
import torch

x = torch.randn(3, requires_grad=True)
y = x + 2 # in case of you roperation the output grad_fn=<> will be changing

print(y)
print(y.grad_fn)

tensor([0.7821, 2.8537, 1.7990], grad_fn=<AddBackward0>)


# Design Model
The model has to implement __init__ and forward function